### ISSUE TITLE
Interested, but need help

### ISSUE THREAD

**Issue by PitbullRaven** [Atemu/backblaze-personal-wine-docker#1]
Hi!
I ran across this when trying to find a solution to get BackBlaze Personal for which Iw as already a subscriber on my Windows machine to work from within unRAID. My Win box bust, and I switched to unRAID, without considering that BackBlaze Personal wouldn't work. Your Docker is maybe my best and last hope to get this to work. However, I have difficulties understanding how to get it to work. What are the prerequisites? I am hoping I can mount two of my shares as drives /mnt/user/backups to Drive D and /mnt/user/appdata to Drive E.

Any pointers will be greatly appreciated.

**Comment by Atemu** [comment]
Have a look at the README, it covers all of your questions afaict. I'm not going to make it cover unRAID-specific stuff but If you have basic Docker and CLI knowledge and come across something that's not clear, it's a bug and needs to be fixed.

Please open an issue if you do.
